const {
  PORT,
  FRONTEND_API_KEY,
  FRONTEND_DOMAIN,
  FRONTEND_URI,
  ANCHOR_WALLET,
  PROGRAM_ID,
  LAND_MERKLE_TREE_ADDRESS,
  RENTAL_MERKLE_TREE_ADDRESS,
  MINT_ADDRESS,
  ANCHOR_PROVIDER_URL,
  WEB_STORAGE_TOKEN,
} = process.env;

export const configs = {
  PORT: PORT ? Number(PORT) : 8888,
  FRONTEND_API_KEY,
  FRONTEND_DOMAIN,
  FRONTEND_URI,
  ANCHOR_WALLET,
  PROGRAM_ID,
  LAND_MERKLE_TREE_ADDRESS,
  RENTAL_MERKLE_TREE_ADDRESS,
  MINT_ADDRESS,
  ANCHOR_PROVIDER_URL,
  WEB_STORAGE_TOKEN,
  WEB3_HEADER: { t: 'sip99' },
  WEB3_NETWORK: 'solana',
};
